### ISSUE TITLE
Stays in -echo mode

### ISSUE THREAD

**Issue by ArtBIT** [tanhauhau/Inquirer.sh#14]
If you source `dist/Inquirer.sh` after running `text_input`, `list_input`, or `checkbox_input`, the shell stays in `stty -echo` mode.

It also uses the “exit on error” option (set -e) that will force the shell to exit on any command with a non-zero exit status, which in turn may break scripts that source the inquirer scripts.

I suggest optionally enabling the `set -e` option is the script is not sourced, or better yet, unset the `e` flag if it was not set prior to the inquirer scripts:

```lang=bash
#!/usr/bin/env bash <- I also recommend this instead of #!/bin/bash
# save the set options
OLD_SET=$-
...
# in cleanup part
if [[ $OLD_SET =~ e ]]
then set -e
else set +e
fi
```

**Comment by ArtBIT** [comment]
Here is my proposed fix: https://github.com/tanhauhau/Inquirer.sh/pull/15

**Comment by tanhauhau** [comment]
@kahkhang need your help on this
