### ISSUE TITLE
didn't clear the terminal

### ISSUE THREAD

**Issue by tanhauhau** [tanhauhau/Inquirer.sh#3]
<img width="901" alt="screen shot 2017-06-25 at 11 02 13 pm" src="https://user-images.githubusercontent.com/2338632/27517170-631c26f4-59fa-11e7-9b37-050a961f2f74.png">

```#!/bin/bash
source checkbox_input.sh

hawker_centres=( 'Old Airport Road Hawker Centre' 'Golden Mile Food Complex' 'Maxwell Food Centre' 'Newton Food Centre' )

checkbox_input selected_hawkers "Which hawker centres do you prefer?" hawker_centres
echo "Selected indices $(join "${selected_hawkers[@]}")"
echo "Selected Hawker Centers:"
for i in $(seq 1 ${#selected_hawkers[@]}); do
  echo "${hawker_centres[${selected_hawkers[$i]}]}"
done
```

Somehow there's this `lex` behind the `Selected Hawker Centers:`

**Comment by kahkhang** [comment]
gg this is a bug, I created another function `print` so that it will clear and print at the same time lol, but yea this is something that needs to be resolved xD
